### ISSUE TITLE
When external is set, folder still created in internal and debug only works when created there

### ISSUE THREAD

**Issue by rancidfrog** [troop/FreeDcam#48]
FreeDCam folder created in main storage even though set as external, with  custom media profile in it.
Also, app looks for debug in main storage not sd card even though save location set as external.

(Pictures are saved externally)

**Comment by troop** [comment]
that internal sd is used to store mediaprofiles opcode bins etc. 
that will stay on internal sd because there is sure that freedcam has full write/read acess wich is not granted on external sd. 
that the same for debugging logs. only pictures/movies gets saved to external sd.

that stuff stored inside internal sd has only a few bytes max 1mb with opcode.
i could store it inside the freedcam cache dir. but then its not acessible for non rooted users.

**Comment by rancidfrog** [comment]
Okay, thanks for explanation
