### ISSUE TITLE
focus problem,  zoom not present, not all controls present.

### ISSUE THREAD

**Issue by muntesco** [troop/FreeDcam#81]
beta 17 end from oggy the last Alfa version.On sony Xperia Z5 focus doesn't work well. It works with manual, scrolling up and down from 0 to 83. But when in Auto just doesn't focus at all. Also a focus circle is white-red, never green.
also, when installing, for a shortest period of time I've seen a whole bunch of controls on the front screen. But, once installed, I have only exposure/focus/white balance. Considering that it's the best camera program I ve found, it's working perfectly with sony sensor (especially turning off the noise reduction) the complete manual mode with all the functions would be excelent.

[https://youtu.be/4ePztjBnpgQ]

**Comment by troop** [comment]
sony did not a good job with the Z5 camera. limited jpeg to 8mp like samsung lol
the z5 is a limted devices. the first i see...
fact is it supports only mf. shutter and manual iso seems not to be supported.

on first start you see all possible ui items because the ui is faster loaded as the camera starts.
when camera is up the ui knows wich buttons should be visible.
so that is correct: 

>  I have only exposure/focus/white balance 

+zoom, its fixed

you can enable contrast and brightness when you set colorcorrection in settings to contrast curve.
that part is not working good and need some optimizations, thats why its hidden that way.

on all my camera2 devices nexus5/lg g4 i dont have problems with focus
