### ISSUE TITLE
3.3.134alpha1 UI problem (Redmi Note 2 "Hermes')

### ISSUE THREAD

**Issue by TaoistHUN** [troop/FreeDcam#82]
Hi.
I downloaded, the last alpha.
It works, but with some UI issues:
- The preview is upside down, and its unable to rotate, the positions of menu elemnets  is correct, just the live view, rotated 180 degree.
- The shutter speed button is missing, and if i change from JPG to DNG,  the jpg's optionts does not gone (sharpness, saturation, zoom, contrast button...)

**Comment by troop** [comment]
> The preview is upside down, and its unable to rotate, the positions of menu elemnets is correct, just the live view, rotated 180 degree.

dont know cant reproduce the problem. try to full deinstall it and install it again.

> 
The shutter speed button is missing

you must first change the manual iso. after that the shutter button is acessible.
mtk handels that stuff like lg. both iso/shutter must get set to deactivate ae.

> and if i change from JPG to DNG, the jpg's optionts does not gone (sharpness, saturation, zoom, contrast button...)

 because all items are visible see #75

**Comment by papersplease** [comment]
Can confirm some UI problems on the same device:
- EV correction slider seems to be stuck at -3.0, [here's the log](https://gist.github.com/papersplease/e0ee768f74732c60230f5e580dffbbe3) for trying to change it
- The preview is not upside down for me, but it doesn't react to 180 degree rotation either. [Here's the log](https://gist.github.com/papersplease/231a725be02656bcb8801210c0d8b0e1) for rotating the device upside down.
- Bottom ISO slider is showing 0 instead of Auto.
- Changing bottom ISO slider doesn't make shutter speed button to appear. ([here's the log](https://gist.github.com/papersplease/72972fee3f623ce5a04bc2ab1f84387f) for trying to change it)

**Comment by TaoistHUN** [comment]
I fully removed, the old one, and clean installed this release.
The Upside down problem solved, but same issues as **papersplease**'s log.
The shutter speed button disappered, and the rotation did not work....

**Comment by troop** [comment]
you are on 134alpha2?

**Comment by papersplease** [comment]
@troop 134alpha2 seemed to fix stuck EV (and #75 as well), all other problems are still there. Bottom ISO slider reads 400 instead of Auto now.

**Comment by TaoistHUN** [comment]
Now I'm on 3.3.134alpha2.
Same problem, the shutter button is  missing, and the bottom ISO slider is showing 0 instead of Auto....

**Comment by papersplease** [comment]
alpha3, everything except 180 degree rotation is working now, thanks for the fix.

**Comment by TaoistHUN** [comment]
Same as above...
Alpha3 Works, except the UI rotation.
BTW I think the earlyer release (beta 17) was better, because, if i  want to take a DNG pic, i dont need the JPG'S postprocessing function buttons (Sharpness, Saturation, contrast...) it is useless with DNGs ...
It was disabled at DNG mode in Beta 17.

**Comment by papersplease** [comment]
@TaoistHUN It affects the preview, and the clipping detection depends on it. Read #75 for the technical reasoning. (although I agree this can be confusing for many people...)

**Comment by troop** [comment]
the cameraui gets no more rotated, but it was dropped along time ago(in a galaxy far far away...). 
im shooting alot vertical and it was anyoing that it keeped rotating at a specific angel.
as sample i have a startracker wich rotates about 360° to avoid startrails. if the phone is mounted there and the tracker reaches 0 or 180° it started continouse switching.

**Comment by TaoistHUN** [comment]
::troop:: , ::papersplease::  THX, Issue closed.
Any hope for an live Histogram, or saveable custom modes ( ISO, Shutter speed, Focus...) Like C1, C2  modes in DSLRs?  I see this awesome function in another camera app (Snap Camera)  and its wery useful.

**Comment by troop** [comment]
live histogram was added along time and got replaced with focuspeak/clipping.
about the save able custom modes we can talk but i dont see the sense behind.
there are situations where you need high iso to avoid motion, in others scenes you want to have that motion trail. you will end in setting it up manual. when you just want to have a well exposured image ae does a good job. freedcam is complicated enough i dont think that will make user live easier lol

**Comment by papersplease** [comment]
Well at least saving all settings like focus/shutter speed would be handy. (for keeping that hyperfocal focus between sessions, for example)

**Comment by troop** [comment]
hm yes call it a design fail.only simple parameters that are not affected from other parameters or affecting other parameters gets saved. thats caused due oems camera fragmentation and my lazyness.
