### ISSUE TITLE
Manual ISO doesn't work on Redmi note 2

### ISSUE THREAD

**Issue by milancheee** [troop/FreeDcam#88]
I haven't seen this issue yet, but I have it for almost a month, I was on Play store version then I tried installing beta versions (from beta9 till beta16 from github) and I just updated to 3.3.135.

If I choose any ISO value from manual controls, ISO is locked on 16383. Changing shutter or ISO doesn't affect it at all. 

I'll gladly provide any info you need, I should state that I'm on the last version of MIUI 7.5.1.0 Global, and S5K3M2 is by Sunny.

edit: Attached Cameraparameters
[Redmi Note 2_CameraParameters.txt](https://github.com/troop/FreeDcam/files/354680/Redmi.Note.2_CameraParameters.txt)

**Comment by milancheee** [comment]
debug
[Redmi Note 2_2016_07_09_04_35_06.txt](https://github.com/troop/FreeDcam/files/356035/Redmi.Note.2_2016_07_09_04_35_06.txt)

**Comment by papersplease** [comment]
It works actually. The problem is with double controls which is a bit confusing, and some mediatek exif bug.
1. The ISO control on the left only affect the preview and exif, not the actual ISO at which it takes the shot.
2. If this control is set to auto and the bottom ISO control is set to anything else, mediatek writes ISO 16383 to exif, but the actual iso at which it takes the shot is taken from the bottom control.

**Comment by milancheee** [comment]
Got you!

ISO controls on the left is just default MIUI/Mediatek ISO control which can be found in default camera app, and those parameters are pretty much fixed.

I thought there was some bug with freedcam, because no matter what manual ISO I choose all pictures end up noisy (even with ISO100). Default MIUI/Mediatek ISO400 with 1/5s exposure looks pretty good, yet if I use freedcam with 1/4s and ISO400 it ends up really noisy. I guess nothing can be done, and Mediatek just sucks with manual controls.
